### ISSUE TITLE
augment with Logeion defs

### ISSUE THREAD

**Issue by balmas** [alpheios-project/mjm#6]
The middle liddell index upon which this index was based is missing many thousands of lemmas that are present in the LSJ index.

The Logeion short definitions file (https://github.com/helmadik/shortdefs) originally derived from both Middle Liddell and LSJ has been manually curated by Helma Dik to have many corrections and additional lemmas. We should augment this file with those, crediting Logeion where the ML definition was edited and where the lemma was added from there.

**Comment by balmas** [comment]
logeion defs have been included.

If the lemma was already present in the file, and the source was ML, and the Logeion def differed, I took the Logeion def, and the source is set to both ML and Logeion

if the lemma was already present in the file and the source was Major, I preferred the Major definition and left it alone

if the lemma was not present in the file, I added it and referenced Logeion as the source.

There are now 107,036 entries in the file (where we had previously only 37,529.

Many proper names are included now that weren't before.

**Comment by balmas** [comment]
You should be able to test this now in the latest 3.3.x QA builds.  The released code will get the old version of the short definitions and QA build will get the newer version.  Example words you can test with:

ῥῖμμα (throw, cast) - missing from the prior version, added by Logeion
εὔρινος (with a good nose) - from ML, edited by Logeion
αἰνέω (praise) definition from Major

**Comment by monzug** [comment]
as said many proper names have a definition now.

found this one that still when linking from the greek def it has no definition found.  see attachment  @balmas  what do we want to do with this?
![homer-iliad](https://user-images.githubusercontent.com/41396793/104332958-b610b600-54be-11eb-9875-8b15e2d3eab6.JPG)

**Comment by balmas** [comment]
ᾍδης and other similar proper names that morpheus parses to lower case are annoying.

We get this weird loop:

lookup Αἵδης 
no morpheus parse, form gives a see reference to ᾍδης
lookup ᾍδης
morpheus parses lemma as ᾅδης
get no definitions found because the entry ᾅδης in the short defs file points at the upper case entry for ᾍδης but our lemma is lower case so we get nothing.


Need to think about the best way to deal with this. Moving this to a new issue.

**Comment by monzug** [comment]
new issue will take care of the open question, this one is verified.
